name: 'Get & Cache Dependencies'
description: 'Get the dependencies and cache them.'
inputs:
  caching:
    description: 'Whether to cache dependencies or not.'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether the cache was used.'
    value: ${{ steps.used-cache.outputs.used }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      if: inputs.caching == 'true'
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash
    - name: Set used-cache output
      id: used-cache
      run: |
        if [ "${{ inputs.caching }}" != "true" ]; then
          echo "used=false" >> $GITHUB_OUTPUT
        elif [ "${{ steps.cache.outputs.cache-hit }}" = "true" ]; then
          echo "used=true" >> $GITHUB_OUTPUT
        else
          echo "used=false" >> $GITHUB_OUTPUT
        fi
      shell: bash